//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADV.InternetCrawler.DataBase.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PointContent
    {
        public int ID { get; set; }
        public int PointID { get; set; }
        public System.DateTime SaveDateTime { get; set; }
        public string ItemName { get; set; }
        public string ItemArticle { get; set; }
        public string ItemUri { get; set; }
        public decimal ItemPrice { get; set; }
        public decimal ItemDiscountPrice { get; set; }
        public string ItemPictureUri { get; set; }
    }
}
