//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADV.InternetCrawler.DataBase.EF
{
    using System;
    using System.Collections.Generic;
    using ADV.InternetCrawler.Models;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Proc_GetDataPointStats : DataPointStatsModel
    {
        [Key]
        new public int PointID { get; set; }
    }
}
